# Default MRBB preset — matches config.py values
name: default
description: Default Mean Reversion BB parameters matching config.py constants

# Bollinger Band parameters
bb_period: 20
bb_std_dev: 2.5
bb_inner_std_dev: 1.0

# VWAP parameters
vwap_period: 50
vwap_confirmation_pct: 0.02

# Keltner Channel / Squeeze parameters
kc_period: 20
kc_atr_multiplier: 1.5
min_squeeze_duration: 6

# RSI parameters
rsi_period: 14
rsi_oversold: 30
rsi_overbought: 70

# ADX / Regime filter
adx_period: 14
adx_threshold: 22.0
use_regime_filter: true

# Signal parameters
reversion_target: 0.9
max_holding_bars: 50

# Risk parameters
risk_per_trade: 0.02
max_position_pct: 0.25
stop_atr_multiplier: 2.5
